name: Splunk Log Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  analyze-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch logs
        run: |
          source venv/bin/activate
          python scripts/fetch_logs.py

      - name: Quantum anomaly detection
        run: |
          source venv/bin/activate
          python scripts/quantum_detect.py

      - name: GenAI summary
        run: |
          source venv/bin/activate
          python scripts/genai_summary.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-report
          path: output/report.md
